# Generated by Django 5.0.6 on 2024-07-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_time',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
